//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notepad.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTENT
    {
        public byte Id { get; set; }
        public string Theme { get; set; }
        public string Detail { get; set; }
        public Nullable<byte> Personal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual TBLPERSONAL TBLPERSONAL { get; set; }
    }
}
